### ISSUE TITLE
Name and steamId parsing error

### ISSUE THREAD

**Issue by Outpox** [csprance/node-misrcon#2]
Hey there

I've just faced an issue in MisRCON. I traced the root cause to this library when parsing the status rcon response from the server.

![image](https://user-images.githubusercontent.com/3439246/51417943-dc761200-1b80-11e9-8df6-770266f872f4.png)

We can see that my Steam id and name are between quotes. When I click on the Steam id it opens a steamrep url: `https://steamrep.com/profiles/'76561197979700358'`. As you can see the quotes remains in the url and as such it's not valid.  

I believe it comes from the regexp parsing in `src/parsers/parseStatus.ts`#L106  
The status response looks like
```xml
<?xml version="1.0"?>
<methodResponse>
    <params>
        <param>
            <value>
                <string>-----------------------------------------
                    Server Status:
                    name: Miscreated TDM Tournament
                    ip: DESKTOP-LMD8U3C
                    version: 1.0.0.1008
                    level: Multiplayer/islands
                    gamerules: Miscreated
                    time: 07:11
                    players: 24/50
                    round time remaining: 0:00
                    uptime: 01:13:06
                    next restart in: 23:39:33
                    weather: ClearSky
                    weatherpattern: 1
                    -----------------------------------------
                    Connection Status:
                    steam: '76561197979700358'  name: 'Outpox'  entID:'201703' id: '4'  ip: ''  ping: '55'  state: '3'  profile: '0'
                </string>
            </value>
        </param>
    </params>
</methodResponse
```

The regexp currently used for the steamid and name are valid, however they return the quotes as well.
```ts
const steamIdRE = new RegExp('steam: (.*)  name:');
const nameRE = new RegExp('name: (.*)  entID:');
```
So in my case `steamidRE = "'76561197979700358'"` and `nameRE  = "'Outpox'"`. Then these values are trimmed but trim() doesn't remove quotes :D

I'm not an expert with regexp but I think it would be possible to surround the capturing group with the quotes to exclude them from the returned value.
```ts
const steamIdRE = new RegExp("steam: '(.*)'  name:");
const nameRE = new RegExp("name: '(.*)' entID:");
```  
But this might cause issue with names containing a quote `'`.

Let me know what you think.

**Comment by csprance** [comment]
I went ahead and fixed this with 50bcfea and I'll update MisRCON with the latest version and cut a new release.
