### ISSUE TITLE
Cannot find module '../secrets'

### ISSUE THREAD

**Issue by Great999lancer** [csprance/node-misrcon#3]
After I do "npm install" and "npm run build".

I have this issue:

===========================================
test/sendRCONCommandToServer.spec.ts:2:32 - error TS2307: Cannot find module '../secrets'.

    2 import { br1, dev, us77 } from '../secrets';
                                     ~~~~~~~~~~~~

 FAIL  test/NodeMisRcon.spec.ts
  ● Test suite failed to run

    TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    test/NodeMisRcon.spec.ts:4:22 - error TS2307: Cannot find module '../secrets'.

    4 import { us75 } from '../secrets';
                           ~~~~~~~~~~~~
=========================================

How can I fix this issue?

Best Regards

**Comment by csprance** [comment]
The tests require access to specific servers to test functionality. If you just comment out those tests and imports it will build just fine.
